image: ghcr.io/foundry-rs/foundry

variables:
  NETWORK_MAINNET_URL: ""
  NETWORK_POLYGON_URL: ""
  NETWORK_GOERLI_URL: ""
  NETWORK_MUMBAI_URL: ""

stages:
  - test

test:
  stage: test
  cache:
    paths:
      - node_modules/
  before_script:
    - apk update && apk add --no-cache wget
    - apk add --update nodejs=16.20.0-r0 npm
  script:
    - npm install
    # - apk update && apk add bash curl git
    # - curl -L https://foundry.paradigm.xyz | bash
    # - source /root/.profile
    # - foundryup
    - npx hardhat test
    - forge test --no-match-contract USDGLO_Fork_Test
