image: node:16.16.0-alpine

variables:
  NETWORK_MAINNET_URL: ""
  NETWORK_POLYGON_URL: ""

stages:
  - test

test:
  stage: test
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npx hardhat test
